/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_greeter_JNIUtils */

#ifndef _Included_com_example_greeter_JNIUtils
#define _Included_com_example_greeter_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_greeter_JNIUtils
 * Method:    makeGlobalRef
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_greeter_JNIUtils_makeGlobalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_greeter_JNIUtils
 * Method:    destroyGlobalRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_greeter_JNIUtils_destroyGlobalRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_greeter_JNIUtils
 * Method:    readGlobalRef
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_example_greeter_JNIUtils_readGlobalRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_greeter_JNIUtils
 * Method:    getEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_greeter_JNIUtils_getEnv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
