// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.ToReflectedMethod.class, "apply", constants$5.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$5.const$5
    );
    static final VarHandle const$2 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("ToReflectedMethod"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetSuperclass.class, "apply", constants$4.const$3);
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetSuperclass"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_BYTE,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
}


