// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final UnionLayout const$0 = MemoryLayout.unionLayout(
        JAVA_BYTE.withName("z"),
        JAVA_BYTE.withName("b"),
        JAVA_SHORT.withName("c"),
        JAVA_SHORT.withName("s"),
        JAVA_INT.withName("i"),
        JAVA_LONG.withName("j"),
        JAVA_FLOAT.withName("f"),
        JAVA_DOUBLE.withName("d"),
        RuntimeHelper.POINTER.withName("l")
    ).withName("jvalue");
    static final VarHandle const$1 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("z"));
    static final VarHandle const$2 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("b"));
    static final VarHandle const$3 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("c"));
    static final VarHandle const$4 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("s"));
    static final VarHandle const$5 = constants$0.const$0.varHandle(MemoryLayout.PathElement.groupElement("i"));
}


