// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$49 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$49() {}
    static final VarHandle const$0 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticObjectMethod"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticObjectMethodV.class, "apply", constants$15.const$0);
    static final VarHandle const$2 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticObjectMethodV"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticObjectMethodA.class, "apply", constants$15.const$0);
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticObjectMethodA"));
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticBooleanMethod"));
}


