// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$89 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$89() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetDirectBufferAddress.class, "apply", constants$4.const$3);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetDirectBufferAddress"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetDirectBufferCapacity.class, "apply", constants$89.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$89.const$2
    );
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetDirectBufferCapacity"));
}


