// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$95 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$95() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNIInvokeInterface_.DetachCurrentThread.class, "apply", constants$3.const$1);
    static final VarHandle const$1 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("DetachCurrentThread"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNIInvokeInterface_.GetEnv.class, "apply", constants$95.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$95.const$2
    );
    static final VarHandle const$5 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("GetEnv"));
}


