// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetStringUTFLength.class, "apply", constants$7.const$5);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetStringUTFLength"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetStringUTFChars.class, "apply", constants$39.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetStringUTFChars"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.ReleaseStringUTFChars.class, "apply", constants$65.const$0);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("ReleaseStringUTFChars"));
}


