// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final VarHandle const$0 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("SetBounds"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BYTE
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(jawt.SynthesizeWindowActivation.class, "apply", constants$104.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$104.const$1
    );
    static final VarHandle const$4 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("SynthesizeWindowActivation"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JAWT_GetAWT",
        constants$90.const$4
    );
}


