// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$84 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$84() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.MonitorEnter.class, "apply", constants$7.const$5);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("MonitorEnter"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.MonitorExit.class, "apply", constants$7.const$5);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("MonitorExit"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetJavaVM.class, "apply", constants$7.const$5);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetJavaVM"));
}


