// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final VarHandle const$0 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("GetComponent"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(jawt.CreateEmbeddedFrame.class, "apply", constants$4.const$3);
    static final VarHandle const$2 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("CreateEmbeddedFrame"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(jawt.SetBounds.class, "apply", constants$103.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$103.const$3
    );
}


