// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticVoidMethodA.class, "apply", constants$26.const$4);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticVoidMethodA"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetStaticFieldID.class, "apply", constants$15.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetStaticFieldID"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetStaticObjectField.class, "apply", constants$39.const$0);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetStaticObjectField"));
}


