// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    static final VarHandle const$0 = constants$98.const$3.varHandle(MemoryLayout.PathElement.groupElement("clipSize"));
    static final VarHandle const$1 = constants$98.const$3.varHandle(MemoryLayout.PathElement.groupElement("clip"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("env"),
        RuntimeHelper.POINTER.withName("target"),
        RuntimeHelper.POINTER.withName("Lock"),
        RuntimeHelper.POINTER.withName("GetDrawingSurfaceInfo"),
        RuntimeHelper.POINTER.withName("FreeDrawingSurfaceInfo"),
        RuntimeHelper.POINTER.withName("Unlock")
    ).withName("jawt_DrawingSurface");
    static final VarHandle const$3 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("env"));
    static final VarHandle const$4 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("target"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jawt_DrawingSurface.Lock.class, "apply", constants$3.const$1);
}


