// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$102 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$102() {}
    static final VarHandle const$0 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("FreeDrawingSurface"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(jawt.Lock.class, "apply", constants$9.const$5);
    static final VarHandle const$2 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("Lock"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(jawt.Unlock.class, "apply", constants$9.const$5);
    static final VarHandle const$4 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("Unlock"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jawt.GetComponent.class, "apply", constants$4.const$3);
}


