// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$81 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$81() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetCharArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetCharArrayRegion"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetShortArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetShortArrayRegion"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetIntArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetIntArrayRegion"));
}


