// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$14 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$14() {}
    static final VarHandle const$0 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewLocalRef"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(JNINativeInterface_.EnsureLocalCapacity.class, "apply", constants$11.const$3);
    static final VarHandle const$2 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("EnsureLocalCapacity"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.AllocObject.class, "apply", constants$4.const$3);
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("AllocObject"));
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewObject"));
}


