// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewLongArray.class, "apply", constants$69.const$0);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewLongArray"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewFloatArray.class, "apply", constants$69.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewFloatArray"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewDoubleArray.class, "apply", constants$69.const$0);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewDoubleArray"));
}


