// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.ReleaseDoubleArrayElements.class, "apply", constants$46.const$0);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("ReleaseDoubleArrayElements"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetBooleanArrayRegion.class, "apply", constants$77.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$77.const$2
    );
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetBooleanArrayRegion"));
}


