// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticBooleanMethodV.class, "apply", constants$18.const$0);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticBooleanMethodV"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticBooleanMethodA.class, "apply", constants$18.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticBooleanMethodA"));
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticByteMethod"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticByteMethodV.class, "apply", constants$18.const$0);
}


