// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$98 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$98() {}
    static final VarHandle const$0 = constants$97.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$1 = constants$97.const$4.varHandle(MemoryLayout.PathElement.groupElement("width"));
    static final VarHandle const$2 = constants$97.const$4.varHandle(MemoryLayout.PathElement.groupElement("height"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("platformInfo"),
        RuntimeHelper.POINTER.withName("ds"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height")
        ).withName("bounds"),
        JAVA_INT.withName("clipSize"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("clip")
    ).withName("jawt_DrawingSurfaceInfo");
    static final VarHandle const$4 = constants$98.const$3.varHandle(MemoryLayout.PathElement.groupElement("platformInfo"));
    static final VarHandle const$5 = constants$98.const$3.varHandle(MemoryLayout.PathElement.groupElement("ds"));
}


