// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticFloatMethodV.class, "apply", constants$24.const$2);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticFloatMethodV"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticFloatMethodA.class, "apply", constants$24.const$2);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticFloatMethodA"));
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("CallStaticDoubleMethod"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JNINativeInterface_.CallStaticDoubleMethodV.class, "apply", constants$25.const$3);
}


