// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewCharArray.class, "apply", constants$69.const$0);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewCharArray"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewShortArray.class, "apply", constants$69.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewShortArray"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewIntArray.class, "apply", constants$69.const$0);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewIntArray"));
}


