// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetByteArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetByteArrayRegion"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetCharArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetCharArrayRegion"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetShortArrayRegion.class, "apply", constants$77.const$2);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetShortArrayRegion"));
}


