// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetStaticBooleanField.class, "apply", constants$44.const$0);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetStaticBooleanField"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetStaticByteField.class, "apply", constants$44.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetStaticByteField"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetStaticCharField.class, "apply", constants$45.const$0);
    static final VarHandle const$5 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetStaticCharField"));
}


