// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("version"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("group")
    ).withName("JavaVMAttachArgs");
    static final VarHandle const$1 = constants$93.const$0.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final VarHandle const$2 = constants$93.const$0.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$3 = constants$93.const$0.varHandle(MemoryLayout.PathElement.groupElement("group"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("reserved0"),
        RuntimeHelper.POINTER.withName("reserved1"),
        RuntimeHelper.POINTER.withName("reserved2"),
        RuntimeHelper.POINTER.withName("DestroyJavaVM"),
        RuntimeHelper.POINTER.withName("AttachCurrentThread"),
        RuntimeHelper.POINTER.withName("DetachCurrentThread"),
        RuntimeHelper.POINTER.withName("GetEnv"),
        RuntimeHelper.POINTER.withName("AttachCurrentThreadAsDaemon")
    ).withName("JNIInvokeInterface_");
    static final VarHandle const$5 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("reserved0"));
}


