// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$100 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$100() {}
    static final VarHandle const$0 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("Lock"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(jawt_DrawingSurface.GetDrawingSurfaceInfo.class, "apply", constants$9.const$1);
    static final VarHandle const$2 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetDrawingSurfaceInfo"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(jawt_DrawingSurface.FreeDrawingSurfaceInfo.class, "apply", constants$9.const$5);
    static final VarHandle const$4 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("FreeDrawingSurfaceInfo"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jawt_DrawingSurface.Unlock.class, "apply", constants$9.const$5);
}


