// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$63 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$63() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetStaticFloatField.class, "apply", constants$47.const$2);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetStaticFloatField"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.SetStaticDoubleField.class, "apply", constants$48.const$0);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetStaticDoubleField"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewString.class, "apply", constants$63.const$4);
}


