// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("PushLocalFrame"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(JNINativeInterface_.PopLocalFrame.class, "apply", constants$4.const$3);
    static final VarHandle const$2 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("PopLocalFrame"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JNINativeInterface_.NewGlobalRef.class, "apply", constants$4.const$3);
    static final VarHandle const$4 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("NewGlobalRef"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JNINativeInterface_.DeleteGlobalRef.class, "apply", constants$10.const$5);
}


