// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final VarHandle const$0 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    static final VarHandle const$1 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNIInvokeInterface_.DestroyJavaVM.class, "apply", constants$3.const$1);
    static final VarHandle const$3 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("DestroyJavaVM"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JNIInvokeInterface_.AttachCurrentThread.class, "apply", constants$8.const$3);
    static final VarHandle const$5 = constants$93.const$4.varHandle(MemoryLayout.PathElement.groupElement("AttachCurrentThread"));
}


