// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final VarHandle const$0 = constants$99.const$2.varHandle(MemoryLayout.PathElement.groupElement("Unlock"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("version"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("GetDrawingSurface"),
        RuntimeHelper.POINTER.withName("FreeDrawingSurface"),
        RuntimeHelper.POINTER.withName("Lock"),
        RuntimeHelper.POINTER.withName("Unlock"),
        RuntimeHelper.POINTER.withName("GetComponent"),
        RuntimeHelper.POINTER.withName("CreateEmbeddedFrame"),
        RuntimeHelper.POINTER.withName("SetBounds"),
        RuntimeHelper.POINTER.withName("SynthesizeWindowActivation")
    ).withName("jawt");
    static final VarHandle const$2 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(jawt.GetDrawingSurface.class, "apply", constants$4.const$3);
    static final VarHandle const$4 = constants$101.const$1.varHandle(MemoryLayout.PathElement.groupElement("GetDrawingSurface"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jawt.FreeDrawingSurface.class, "apply", constants$9.const$5);
}


