// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JNI_GetCreatedJavaVMs",
        constants$97.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JNI_OnLoad",
        constants$7.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JNI_OnUnload",
        constants$10.const$5
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height")
    ).withName("jawt_Rectangle");
    static final VarHandle const$5 = constants$97.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
}


