// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetShortField.class, "apply", constants$40.const$2);
    static final VarHandle const$1 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetShortField"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetIntField.class, "apply", constants$8.const$3);
    static final VarHandle const$3 = constants$2.const$2.varHandle(MemoryLayout.PathElement.groupElement("GetIntField"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(JNINativeInterface_.GetLongField.class, "apply", constants$41.const$4);
}


