// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct JavaVMOption {
 *     char* optionString;
 *     void* extraInfo;
 * };
 * }
 */
public class JavaVMOption {

    public static MemoryLayout $LAYOUT() {
        return constants$91.const$4;
    }
    public static VarHandle optionString$VH() {
        return constants$91.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* optionString;
     * }
     */
    public static MemorySegment optionString$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$91.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* optionString;
     * }
     */
    public static void optionString$set(MemorySegment seg, MemorySegment x) {
        constants$91.const$5.set(seg, x);
    }
    public static MemorySegment optionString$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$91.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void optionString$set(MemorySegment seg, long index, MemorySegment x) {
        constants$91.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle extraInfo$VH() {
        return constants$92.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* extraInfo;
     * }
     */
    public static MemorySegment extraInfo$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$92.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* extraInfo;
     * }
     */
    public static void extraInfo$set(MemorySegment seg, MemorySegment x) {
        constants$92.const$0.set(seg, x);
    }
    public static MemorySegment extraInfo$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$92.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void extraInfo$set(MemorySegment seg, long index, MemorySegment x) {
        constants$92.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


