// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct jawt_DrawingSurface JAWT_DrawingSurface;
 * }
 */
public final class JAWT_DrawingSurface$2 extends jawt_DrawingSurface {

    // Suppresses default constructor, ensuring non-instantiability.
    private JAWT_DrawingSurface$2() {}
}


