// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct jawt_DrawingSurfaceInfo JAWT_DrawingSurfaceInfo;
 * }
 */
public final class JAWT_DrawingSurfaceInfo$1 extends jawt_DrawingSurfaceInfo {

    // Suppresses default constructor, ensuring non-instantiability.
    private JAWT_DrawingSurfaceInfo$1() {}
}


