// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct jawt JAWT;
 * }
 */
public final class JAWT$3 extends jawt {

    // Suppresses default constructor, ensuring non-instantiability.
    private JAWT$3() {}
}


