// Generated by jextract

package com.sineaggi.jniutils.internal.jni;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct jawt_Rectangle JAWT_Rectangle;
 * }
 */
public final class JAWT_Rectangle$0 extends jawt_Rectangle {

    // Suppresses default constructor, ensuring non-instantiability.
    private JAWT_Rectangle$0() {}
}


