# This is the main CI workflow to test that the package can be built on various platforms

name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches-ignore: []

env: {}

jobs:

  clippy:
    name: Gradle build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env: {}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - name: Linux x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            # Macos
          - name: Macos x86_64
            os: macos-latest
            target: x86_64-apple-darwin
          - name: Macos aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            # Windows
          - name: Windows msvc x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Environment
        run: ${{ matrix.setup_env }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
          check-latest: true
      - name: Setup and execute Gradle 'build' task
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2'
          arguments: 'build'
